### ISSUE TITLE
Appsflyer Subscriptions vs Renewals

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#124]

**Comment by Farahalfayez** [comment]
Hey guys, what's the update on this issue? It's a high priority for me. @Shimaa-Hassan @EmanHylooz

**Comment by EmanHylooz** [comment]
@Farahalfayez this task is done and will be reflected on production today. @Shimaa-Hassan will let you know once it is done.

**Comment by Shimaa-Hassan** [comment]
@Farahalfayez I put it in production but I need to test it. So I will test it in sunday ISA

**Comment by Shimaa-Hassan** [comment]
@Farahalfayez please don't run any campaigns until test it in production.

**Comment by Farahalfayez** [comment]
@Shimaa-Hassan How did you get access to the non_organic _in_app_events report? Last time you sent it to me. I can't seem to find the data anywhere. Do we need to upgrade to get this report? How did you test it on Appsflyer without upgrading?

**Comment by Shimaa-Hassan** [comment]
@Farahalfayez 

First Login in appsflyer

IOS App:
https://hq.appsflyer.com/export/id976628194/in_app_events_report/v5?api_token=c86c5264-e861-4d4e-8c63-710fe04d3bb6&from=2017-08-16&to=2017-08-23

Android App:
https://hq.appsflyer.com/export/com.abjjad.app/in_app_events_report/v5?api_token=c86c5264-e861-4d4e-8c63-710fe04d3bb6&from=2017-08-16&to=2017-08-23

You can change "from" and "to" date

In reports you will see _subscriptionNumber in "Event Value" with "Event Name" Subscription

**Comment by Farahalfayez** [comment]
@Shimaa-Hassan 

When I click on the links you sent the files get downloaded automatically. And the links won't open on their own. When I click on export data from my account, I only have these reports: 

![export data](https://user-images.githubusercontent.com/30770652/29606226-ac5def50-87fe-11e7-87d5-4f0749b1e0e7.PNG)

![export data 2](https://user-images.githubusercontent.com/30770652/29606265-c60e61aa-87fe-11e7-988d-d763f3e8b448.PNG)

![export data 3](https://user-images.githubusercontent.com/30770652/29606278-ccd2afd2-87fe-11e7-8b60-26dec27041c5.PNG)

![export data 4](https://user-images.githubusercontent.com/30770652/29606284-d2b121ea-87fe-11e7-9869-0d6f60c81be0.PNG)

![export data 5](https://user-images.githubusercontent.com/30770652/29606291-da212a7e-87fe-11e7-9e1a-bd977c709e3a.PNG)

Can you send me the exact steps instead of links please? Thanks :)

**Comment by Shimaa-Hassan** [comment]
@Farahalfayez I don't know How to export data from appsflyer UI I just know the links that help me in testing purpose So please ask appsflyer team about how to export in app events reports.

**Comment by EmanHylooz** [comment]
@Farahalfayez are we good here or is there anything further needed?

**Comment by Farahalfayez** [comment]
@EmanHylooz Actually to get access to these reports on the dashboard we need to have a premier account! But I tried Shimaa's way changing in pulling the data from the links with different dates and it worked but only for non-organic events. I expect premier accounts will be really costly and you need to contact sales to get a quote.. not sure if we can afford or if it's worth it. What do you think? For now we can know the subscription number (renewal or 1st, 2nd, etc) for users acquired from ad campaigns.

**Comment by EmanHylooz** [comment]
@Farahalfayez I guess for now it is okay to get this data coming from paid ads? unless you advice otherwise, it is your call.

**Comment by Farahalfayez** [comment]
I guess since Shimaa added this subscription number as a parameter then this data can be pulled from the database for all subscriptions regardless of source (attribution). @Shimaa-Hassan Am I right? 

@EmanHylooz  If that is true, then pulling the non-organic subscriptions data from Appsflyer and having the all subscription data in the database would be enough. Definitely not worth investing in a premier account just for this.. when there are higher priority apps to invest in.

**Comment by EmanHylooz** [comment]
True, I agree. Yes most probably (99.9%) we can pull it from data base
unless Shimaa says otherwise.

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
So we are good, shall we close this issue?

**Comment by Farahalfayez** [comment]
Yes sure. @EmanHylooz
